[package]
name = "delivery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.*"
lerp = "0.4.*"
rand = "0.8.*"